#!/bin/bash
#PBS -S /bin/bash
#PBS -o /home/vla/python/nls_drc/sim_incomplete/2b.unnorm_incomplete_control/drc_ctrol.log 
#PBS -j oe
#PBS -l nodes=1:ppn=1,mem=2048mb,walltime=72:00:00

module load miniconda/3
source activate bitc_race
cd /home/vla/python/nls_drc/sim_incomplete/2b.unnorm_incomplete_control
date
python /home/vla/python/nls_drc/scripts/run_nls_sim.py --data_dir /home/vla/python/nls_drc/sim_incomplete/1.generate_curves --data_file drc_sim_unnorm_incomplete --out_dir /home/vla/python/nls_drc/sim_incomplete/2b.unnorm_incomplete_control --fitting_with_control   
date 
