#!/bin/bash
#PBS -S /bin/bash
#PBS -o /home/vla/python/nls_drc/fluorescence/1a.unnorm_control/f_unnorm_ctrol.log 
#PBS -j oe
#PBS -l nodes=1:ppn=1,mem=2048mb,walltime=72:00:00

module load miniconda/3
source activate bitc_race
cd /home/vla/python/nls_drc/fluorescence/1a.unnorm_control
date
python /home/vla/python/nls_drc/scripts/run_nls_fluorescence.py --data_dir /home/vla/python/nls_drc/fluorescence/input --out_dir /home/vla/python/nls_drc/fluorescence/1a.unnorm_control  --fitting_with_control  
date 
